[project]
name = "kan-compare"
version = "0.1.0"
dependencies = [
    "torch>=2.4.0+cu118",
    "numpy>=2.0.1",
    "torchvision>=0.19.0+cu118",
]
requires-python = ">=3.12"


[tool.pdm]
distribution = false
